---
stages:
  - test

test:
  stage: test
  image: alpine:3.12.0
  tags:
    - minipig
  before_script:
    - apk add -U ansible
    - ansible --version
    - echo -e '[defaults]\nroles_path = ../' > ansible.cfg
    - cat ansible.cfg
  script:
    - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
