---
stages:
  - syntax
  - test

syntax_check:
  stage: syntax
  image: alpine:3.12
  tags:
    - minipig
  variables:
    ANSIBLE_CONFIG: "${PWD}/ansible.cfg"
  before_script:
    - apk add -U ansible
    - ansible --version
    - printf "[defaults]\nroles_path = $(dirname ${PWD})\n" > "${ANSIBLE_CONFIG}"
  script:
    - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

molecule:
  stage: test
  image: docker:stable
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
  tags:
    - minipig
  before_script:
    - apk add -U ansible py3-pip docker-py
    - python3 -m pip install molecule[docker]
    - ansible --version
    - molecule --version
    - id
    - ls -la /var/run/
    - docker info
  script:
    - molecule test --driver-name=docker --destroy=always
