---
stages:
  - test

test_simple:
  stage: test
  image: dockage/alpine:3.11-openrc
  tags:
    - minipig
  variables:
    ANSIBLE_CONFIG: "${PWD}/ansible.cfg"
  before_script:
    - apk add -U ansible
    - ansible --version
    - printf "[defaults]\nroles_path = $(dirname ${PWD})\n" > "${ANSIBLE_CONFIG}"
    - mkdir /run/openrc && touch /run/openrc/softlevel
    - rc-status -a
  script:
    - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
    - ansible-playbook tests/test.yml -i tests/inventory --connection local

test_molecule:
  stage: test
  image: alpine:3.12.0
  services:
    - docker:dind
  tags:
    - minipig
  before_script:
    - apk add -U ansible py3-pip
    - pip install molecule molecule-docker
    - ansible --version
  script:
    - molecule test
