---
stages:
  - test

test:
  stage: test
  image: alpine:3.12.0
  tags:
    - minipig
  before_script:
    - apk add -U ansible
    - ansible --version
  script:
    - printf '[defaults]\nroles_path=../' >ansible.cfg
    - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
