---
stages:
  - test

test:
  stage: test
  image: dockage/alpine:3.11-openrc
  tags:
    - minipig
  variables:
    ANSIBLE_CONFIG: "${PWD}/ansible.cfg"
  before_script:
    - apk add -U ansible
    - ansible --version
    - printf "[defaults]\nroles_path = $(dirname ${PWD})\n" > "${ANSIBLE_CONFIG}"
  script:
    - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
    - ansible-playbook tests/test.yml -i tests/inventory --connection local
