---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/dockage/alpine:3.11-openrc
provisioner:
  name: ansible
  env:
    MOLECULE_NO_LOG: "false"
verifier:
  name: ansible
